# Feel free to delete these and replace with your workflow

name: Rubocop

on: [push]

jobs:
  action_default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter Action - Default
      uses: andrewmcodes/rubocop-linter-action@master # Replace with version, branch, or commit sha if needed e.g. `andrewmcodes/rubocop-linter-action@v3.0.0`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  action_with_config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter Action - Config
      uses: andrewmcodes/rubocop-linter-action@master # Replace with version, branch, or commit sha if needed e.g. `andrewmcodes/rubocop-linter-action@v3.0.0`
      with:
        action_config_path: '.github/config/rubocop_linter_config.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  basic_rubocop:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Ruby 2.7
      uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        gem install bundler:2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Rubocop
      run: bin/rubocop
